version: "2"
services:
  web:
    image: node:6
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c 'npm install && npm start'
    ports: 
      - "3000:3000"
    depends_on:
      - mongo
      - mysql
    links:
      - mongo
      - mysql
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./database/setup:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=database_development